mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
   
    path("", include("polls.urls")),
    path("polls/", include("polls.urls")),
   
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),  # 로그인, 로그아웃, 비밀번호 변경 등 기본 제공 URL 포함
       
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
]
    
    

polls/urls.py
from django.urls import path
from . import views


app_name = "polls"  # 네임스페이스 지정
  
  
urlpatterns = [
    # path('', views.index, name='index'),
    # path("<int:question_id>/", views.detail, name="detail"),
    # path("<int:question_id>/vote/", views.vote, name="vote"),
    # path("<int:question_id>/results/", views.results, name="results"),
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
   
   
    path('test', views.TestView.as_view(), name='testView'),
    path("test/questions/", views.test_question_list, name="questions_test"),
 


   # ✅ 슬래시 제거
    path("questions/", views.QuestionListView.as_view(), name="questions"), 
    path("questions/<int:pk>/", views.QuestionDetailView.as_view(), name="question_detail"),
    path("questions/create/", views.QuestionCreateView.as_view(), name="question_create"),
    path("questions/update/<int:pk>/", views.QuestionUpdateView.as_view(), name="question_update"),
    path("questions/delete/<int:pk>/", views.QuestionDeleteView.as_view(), name="question_delete"),
 
   
 
   # 질문 선택등록
   path("questions/<int:question_id>/add_choice/", views.ChoiceCreateView.as_view(), name="choice_create"),
 
 
]

polls/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
        
    #연습용 필드 추가
    #test_fileld=models.CharField(max_length=50, default='임시')
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='최근에 게시되었나요?',
    )
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        
    def is_published(self):
        return self.pub_date <= timezone.now()     
            
    def __str__(self):
        return self.question_text
    

    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text =models.CharField(max_length=200)
    votes =models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
    
        

polls/forms.py
from django import forms
from .models import Question, Choice

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']
        widgets = {
            'question_text': forms.TextInput(attrs={'class': 'form-control input-h3'}),
            'pub_date': forms.DateTimeInput(attrs={
                'class': 'form-control input-h3', 
                'type': 'datetime-local'
            }),
        }


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']
        
        
        
        
        

polls/views.py
from django.shortcuts import render, get_object_or_404

from .forms import QuestionForm ,ChoiceForm
from .models import Question, Choice
from django.http import HttpResponseRedirect
from django.urls import reverse ,reverse_lazy
from django.views.generic import ListView
from django.db.models import F
from django.views import generic
from django.views.generic.edit import CreateView 
from django.utils import timezone
from django.db.models import Count


#✅ index 전체 질문중 5개만 조회 (FBA 기반 View)
# index(최신글 list)
# def index(request):
# 	# return HttpResponse("Hello) 기존코드	
# 	latest_question_list = Question.objects.order_by("-pub_date")[:5]
# 	context = {"latest_question_list": latest_question_list}
# 	return render(request, "polls/index.html", context)


# #✅ detail : 상세조회
# def detail(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, "polls/detail.html", {"question": question})



# #  ✅ results : 결과보기
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html", {"question": question})


# #✅ vote : 투표하기 
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)    
#     try:
#         selected_choice= question.choice_set.get(pk=request.POST["choice"])        
#     except (KeyError, Choice.DoesNotExist):
#         # 선택하지 않고 제출한 경우 다시 질문 페이지로
#         return render(request, "polls/detail.html", {
# 		  		"question": question,
# 			  	 "error_message": "선택을 하지 않았습니다.",
# 		    })
#     else:
#       selected_choice.votes += 1
#       selected_choice.save()    
#       # POST 성공 시 리디렉션
#       return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))



    # print("== Vote View Called ==")
    # print(f"Question ID: {question_id}")
    # print(f"Request method: {request.method}")
    # print(f"POST data: {request.POST}")  # POST 방식일 경우 폼 데이터 출력



# 메인 페이지 (질문 목록)
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"
    def get_queryset(self):
        """
        현재 시간 이전에 게시된 질문만 반환
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
    
# 질문 상세 페이지
class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    context_object_name = "question"
    
    def get_queryset(self):
        """
        미래에 게시될 질문은 제외하고, 현재까지 게시된 질문만 보여줌
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
 
 
# 결과 페이지
class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"
    context_object_name = "question"
 
 
# 투표 처리 로직
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message":"You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))





class TestView(ListView):
    template_name = "polls/test.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]







class QuestionListView(ListView):
    model = Question  # 어떤 모델의 데이터를 보여줄지
    template_name = 'polls/question_list.html' 
    # 사용할 템플릿 경로
    
    context_object_name = 'question_list'
    # 템플릿에서 사용할 객체 이름
    
    paginate_by = 10  # 페이지당 항목 수 (선택사항)
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')
    
    
    

class QuestionCreateView(CreateView):
    model = Question
    fields = ['question_text', 'pub_date']  # 폼에서 입력받을 필드
    template_name = 'polls/question_form.html'
    success_url = reverse_lazy('polls:index')  # 저장 후 이동할 URL




class QuestionUpdateView(generic.UpdateView):
    model = Question
    form_class = QuestionForm
    #fields = ["question_text", "pub_date"]
    template_name = "polls/question_update.html"
    success_url = reverse_lazy("polls:index")
    
    
class QuestionDeleteView(generic.DeleteView):
    model = Question
    success_url = reverse_lazy("polls:index")   
    
    
    
class QuestionDetailView(DetailView):
    model = Question
    template_name = 'polls/question_detail.html'
    context_object_name = 'question'  # 템플릿에서 사용할 변수명
   



#유저가 질문에 대한 선택지(Choice)를 추가할
class ChoiceCreateView(CreateView):
    model =Choice
    form_class = ChoiceForm
    template_name=  "polls/choice_form.html"
    
    def form_valid(self, form):
        question_id = self.kwargs["question_id"]
        question = get_object_or_404(Question, pk=question_id)
        form.instance.question = question
        return super().form_valid(form)
    
    
    def get_success_url(self):
        return reverse_lazy('polls:question_detail', kwargs={'pk': self.kwargs['question_id']})



def test_question_list(request):
    #questions = Question.objects.all()
    #questions = Question.objects.annotate(num_choices=Count('choice')).filter(num_choices__gt=0)

    questions = Question.objects.annotate(num_choices=Count('choice')).order_by('-num_choices')


    return render(request, 'polls/question_test_list.html', {'questions': questions})

templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head> 
    {% block title %}<title>Polls</title> {% endblock %}
    {% include "polls/head.html" %}
    {% block css %}{% endblock %}
</head>
<body>
    {% include "polls/header.html" %}

    <main>
        {% block content %}
        <!-- 자식 템플릿에서 이 부분이 채워집니다 -->
        {% endblock %}
    </main>

    {% include "polls/footer.html" %}

     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/polls/choice_form.html
{% extends "polls/base.html" %}
{% load static %}


{% block content %}
  
  <h2>선택지 추가</h2>
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">등록</button>
  </form>


{% endblock %}

templates/polls/detail.html
{% extends "polls/base.html" %}
{% load static %}


{% block title %}
<title>{{ question.question_text }}</title>
{% endblock %}


{% block css %}
 <link rel="stylesheet" href="{% static 'polls/detail.css' %}">
{% endblock %}




{% block content %}
<div class="detail-container">
  <h2 class="question-title">{{ question.question_text }}</h2>


 <form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  <ul class="choice-list">
    {% for choice in question.choice_set.all %}
    <li>
        <label>
            <input type="radio" name="choice" value="{{ choice.id }}">
            {{ choice.choice_text }}
        </label>        
    </li>
    {% endfor %}
  </ul>
 <button type="submit">투표하기</button>
</form>


</div>
{% endblock %}

templates/polls/footer.html
<footer>
    <div class="site-footer">
        <p>&copy; 2025 Django Polls. All rights reserved.</p>
        <p>
            <a href="{{ github_url|default:'https://github.com/yourusername' }}">My GitHub</a> |
            <a href="/terms">Terms of Service</a>
        </p>
    </div>
</footer>

templates/polls/head.html
{% load static %}

<head>
    <meta charset="UTF-8"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'polls/css/styles.css' %}"> 
    <link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}"> 
</head>

templates/polls/header.html
<header>
    <div class="site-header">
        <h1 class="site-title">설문조사 시스템</h1>
        <nav class="site-nav">
            <ul>
                <li><a href="{% url 'polls:index' %}">HOME</a></li>
                <li><a href="{% url 'polls:questions'  %}">질문목록</a></li>
                <li><a href="{% url 'polls:questions_test'  %}">질문테스트</a></li>


                {% if user.is_authenticated %}
                <li>
                <form method="post" action="{% url 'logout' %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="nav-button">로그아웃</button>
                </form>
                </li>
                {% else %}
                <li><a href="{% url 'login' %}" class="nav-button">로그인</a></li>
                <li><a href="{% url 'signup' %}" class="nav-button">회원가입</a></li>
                {% endif %}

            </ul>
        </nav>
    </div>
</header>

templates/polls/index.html
{% extends "polls/base.html" %}
{% load static %}


{% block title %}
<title>질문 목록</title>
{% endblock %}

{% block content %}
<h1 class="mt-5 mb-5">
    <span class="text-primary">
       <img src="{% static 'polls/images/f86c4bc4e00739dc.png' %}"
        alt="질문 목록" width="80" height="80">
    </span>
    질문 목록
</h1>



{% if latest_question_list %}
<ul class="question">
    {% for question in latest_question_list %}
    <li class="text-start">
        <a href="{% url 'polls:detail' question.id %}">
            {{ question.question_text }}

        </a>

        
     <div class="text-muted mt-2">        
       <a href="{% url 'polls:question_create'  %}" class="btn btn-sm  bg-gray">글생성</a>        
        <a href="{% url 'polls:question_update' question.pk %}" class="btn btn-sm btn-warning">수정</a>
        <form method="post" action="{% url 'polls:question_delete' question.pk %}" class="d-inline">
              {% csrf_token %}
         <button type="submit" class="btn btn-sm  btn-danger">삭제</button>
       </form>
    </div>
    
  
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

templates/polls/question_form.html
{% extends 'polls/base.html' %}



{% block content %}
<div class="container mt-5" style="max-width: 800px;">
  <div class="card shadow rounded-4 border-0">
    <div class="card-header bg-gray text-white rounded-top-4 py-3 px-4">
      <h4 class="mb-0">📝 질문 입력</h4>
    </div>
    <div class="card-body px-4 py-4">
      <form method="post" novalidate>
        {% csrf_token %}

        <div class="mb-3">
          <label for="id_question_text" class="form-label fw-semibold">질문 내용</label>
          <input type="text" name="question_text" class="form-control rounded-3 shadow-sm input-h3"
                 id="id_question_text" placeholder="질문을 입력하세요"
                 value="{{ form.question_text.value|default:'' }}">
        </div>

        <div class="mb-4">
          <label for="id_pub_date" class="form-label fw-semibold">게시 날짜</label>
          <input type="datetime-local" name="pub_date" class="form-control rounded-3 shadow-sm input-h3"
                 id="id_pub_date" value="{{ form.pub_date.value|default:'' }}">
        </div>

        <div class="d-flex justify-content-end gap-2">
          <a href="{% url 'polls:index' %}" class="btn btn-outline-secondary rounded-3 px-4">취소</a>
          <button type="submit" class="btn bg-gray rounded-3 px-4">등록</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/polls/question_list.html
{% extends 'polls/base.html' %}


{% block content %}
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2>질문 목록</h2>
    <a href="{% url 'polls:question_create' %}" class="btn btn-primary">+ 새 질문</a>
  </div>

  {% if object_list %}
    <ul class="list-group">
      {% for question in object_list %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href="{% url 'polls:question_detail' question.pk %}">{{ question.question_text }}</a>
          <small class="text-muted">{{ question.pub_date }}</small>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>등록된 질문이 없습니다.</p>
  {% endif %}
</div>
{% endblock %}

templates/polls/question_test_list.html
{% extends "polls/base.html" %}
{% block content %}

<h1>질문 테스트 목록</h1>
{% for question in questions %}

  <ul>    
     {{ question.question_text }} (선택지 수: {{question.num_choices }})
  </ul>

  <hr>
{% endfor %}

{% endblock %}

templates/polls/question_update.html
{% extends 'polls/base.html' %}



{% block content %}
<div class="container mt-5" style="max-width: 800px;">
  <div class="card shadow rounded-4 border-0">
    <div class="card-header bg-gray text-white rounded-top-4 py-3 px-4">
      <h4 class="mb-0">✏️ 질문 수정</h4>
    </div>
    <div class="card-body px-4 py-4">
      <form method="post" novalidate>
        {% csrf_token %}

        <div class="mb-3">
          <label for="id_question_text" class="form-label fw-semibold">질문 내용</label>
          {{ form.question_text }}
        </div>

        <div class="mb-4">
          <label for="id_pub_date" class="form-label fw-semibold">게시 날짜</label>
             {{ form.pub_date }}
        </div>

        <div class="d-flex justify-content-end gap-2">
          <a href="{% url 'polls:index' %}" class="btn btn-outline-secondary rounded-3 px-4">취소</a>
          <button type="submit" class="btn bg-gray rounded-3 px-4">수정</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/polls/results.html
{% extends "polls/base.html" %}
{% load static %}

{% block title %}<title>결과</title>{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'polls/results.css' %}">
{% endblock %}


{% block content %}
<div class="results-container">
  <h2>{{ question.question_text }}</h2>
  <ul class="results-list">
    {% for choice in question.choice_set.all %}
      <li>
        <span>{{ choice.choice_text }}</span>
        <span>{{ choice.votes }}표</span>
      </li>
    {% endfor %}
  </ul>
  <a class="back-link" href="{% url 'polls:index' %}">← 돌아가기</a>
</div>
{% endblock %}

templates/polls/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    테스트 페이지
</body>
</html>

templates/polls/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


    투표
    
    
</body>
</html>